const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const { indexSource, initParser } = require('../out/indexer');
const { CallGraph } = require('../out/graph');

async function graphOf(files) {
  await initParser(path.join(__dirname, '..'));
  const graph = new CallGraph();
  for (const [file, source] of Object.entries(files)) {
    graph.setFile(file, indexSource(file, source));
  }
  graph.resolveEdges();
  const status = (name) => {
    const node = graph.allNodes().find((n) => n.name === name);
    assert.ok(node, `function ${name} was not indexed`);
    return graph.usageStatus(node);
  };
  return { graph, status };
}

test('JS/TS: live code that is never called directly is not marked unused', async () => {
  const { status } = await graphOf({
    '/app/src/list.tsx': `
      import { Card } from './card';
      function usedAsCallback(x) { return x; }
      const handleSubmit = () => {};
      export function List({ items }) {
        return <ul onSubmit={handleSubmit}>{items.map(usedAsCallback).map((i) => <Card key={i} />)}</ul>;
      }
    `,
    '/app/src/card.tsx': `export function Card() { return <li />; }`,
    '/app/src/legacy.js': `
      function viaExportsObject() {}
      function unusedHelper() { return 1; }
      function selfRecursive(n) { return n ? selfRecursive(n - 1) : 0; }
      module.exports = { viaExportsObject };
    `,
    '/app/src/lib.ts': `export function exportedButUnused() {}`,
    '/app/src/app/page.tsx': `export default function Page() { return null; }`,
    '/app/src/app/api/route.ts': `export async function GET() { return new Response('ok'); }`,
    '/app/src/list.test.ts': `function buildFixture() { return []; }`,
    '/app/src/server.js': `
      class Store { find() {} }
      function makeStore() { return new Store(); }
      module.exports.start = () => { const s = makeStore(); return s; };
    `,
    '/app/src/hooks.ts': `
      export function useSave() {
        return useMutation({ mutationFn: save, onSuccess: () => toast('ok'), onError: (e) => toast(e) });
      }
      function save() {}
      function readFile(f) { const r = new FileReader(); r.onload = () => done(r.result); r.readAsText(f); }
    `,
  });

  assert.equal(status('usedAsCallback'), 'active', 'passed as a callback');
  assert.equal(status('handleSubmit'), 'active', 'used as a JSX event handler');
  assert.equal(status('Card'), 'active', 'rendered as <Card />');
  assert.equal(status('viaExportsObject'), 'exported-unused', 'listed in module.exports but used nowhere');
  assert.equal(status('exportedButUnused'), 'exported-unused', 'exported but unused here');
  assert.equal(status('Page'), 'entry', 'default export is called by the framework');
  assert.equal(status('GET'), 'entry', 'route handler');
  assert.equal(status('buildFixture'), 'entry', 'functions in test files run under the test runner');
  assert.equal(status('makeStore'), 'active', 'used inside a function assigned to module.exports');
  assert.equal(status('start'), 'exported-unused', 'the exported function itself');
  assert.equal(status('find'), 'exported-unused', 'class methods are public API: exported, never plainly unused');
  assert.equal(status('onSuccess'), 'entry', 'object-property callback handed to a library');
  assert.equal(status('onError'), 'entry', 'object-property callback handed to a library');
  assert.equal(status('onload'), 'entry', 'assigned onto an object the runtime calls');
  assert.equal(status('readFile'), 'unused', 'a real unused function next to them is still caught');
  assert.equal(status('unusedHelper'), 'unused', 'never referenced anywhere');
  // Name-based and conservative: a self-call counts as a use, so this is not flagged.
  assert.equal(status('selfRecursive'), 'active');
});

test('Go: methods are indexed, and registrations, interfaces and tests count as use', async () => {
  const { graph, status } = await graphOf({
    '/app/internal/controllers/site.go': `
      package controllers
      type SiteController struct{}
      func (t *SiteController) ListAll(w int) {}
      func (t *SiteController) unusedMethod() {}
      func Register(r Router, t *SiteController) { r.Get("/sites", t.ListAll) }
      func helper() {}
      func ExportedNoUse() {}
      type MyErr struct{}
      func (e MyErr) Error() string { return "x" }
    `,
    '/app/cmd/main.go': `package main\nfunc main() {}`,
    '/app/internal/db/sqlcgen/db.go': `// Code generated by sqlc. DO NOT EDIT.\npackage sqlcgen\nfunc WithTx() {}`,
    '/app/internal/controllers/site_test.go': `package controllers\nfunc TestListAll(t *T) {}`,
  });

  assert.ok(graph.allNodes().some((n) => n.name === 'ListAll'), 'Go methods must be indexed');
  assert.equal(status('ListAll'), 'active', 'method value passed to the router');
  assert.equal(status('unusedMethod'), 'unused');
  assert.equal(status('helper'), 'unused');
  assert.equal(status('ExportedNoUse'), 'exported-unused', 'capitalised Go names are exported');
  assert.equal(status('Error'), 'entry', 'satisfies the error interface');
  assert.equal(status('main'), 'entry');
  assert.equal(status('WithTx'), 'entry', 'generated code is never suggested for removal');
  assert.equal(status('TestListAll'), 'entry');
});

test('uses count as dependencies: JSX tags, callbacks and router registrations', async () => {
  const { graph } = await graphOf({
    '/app/card.tsx': `export function Card() { return <li />; }`,
    '/app/pages.tsx': `
      export function Home() { return <Card />; }
      export function About() { return <div><Card /></div>; }
      export function Form() { return <form onSubmit={handleSubmit} />; }
      function handleSubmit() {}
    `,
    '/app/routes.go': `package r\nfunc Register(r R, t *T) { r.Get("/", t.List) }\nfunc (t *T) List() {}`,
  });
  const callers = (name) => [...graph.allNodes().find((n) => n.name === name).callers].map((id) => id.split(':').pop()).sort();
  assert.deepEqual(callers('Card'), ['About', 'Home'], 'rendering <Card /> depends on Card');
  assert.deepEqual(callers('handleSubmit'), ['Form'], 'passing a handler depends on it');
  assert.deepEqual(callers('List'), ['Register'], 'registering a method value depends on it');
});

test('reach counts every function that reaches this one through calls', async () => {
  const { graph } = await graphOf({
    '/app/a.js': `
      function leaf() {}
      function mid() { leaf(); }
      function top1() { mid(); }
      function top2() { mid(); }
      function root() { top1(); top2(); }
    `,
  });
  const reach = (name) => graph.reachCount(graph.allNodes().find((n) => n.name === name).id);
  assert.equal(reach('leaf'), 4); // mid, top1, top2, root
  assert.equal(reach('mid'), 3);
  assert.equal(reach('root'), 0);
});
