/**
 * Blast Radius - Markdown context for LLMs.
 *
 * Turns what Blast Radius already knows - the call graph, risk scores, git
 * history and features - into Markdown an assistant can be handed before it
 * touches the code. Two documents:
 *
 *   functionMarkdown  one function: its code, callers, callees, features, risk
 *   featureMarkdown   one feature: its commits, owners, files, every function it
 *                     touched with code, how they connect, and - the part an LLM
 *                     cannot infer from reading the feature alone - what OUTSIDE
 *                     the feature calls into it and could break
 *
 * Everything written is a measured fact (graph edges, git history, scores).
 * Nothing is summarised or guessed, so the documents are safe to paste into a
 * prompt as ground truth.
 *
 * Dependency-free (no vscode import) so scripts/check-llm.js can verify it.
 */
import type { Feature, FeaturesPayload } from "./features";
import { formulaText, RiskBreakdown } from "./score";

export interface FunctionInfo {
  id: string;
  name: string;
  /** Workspace-relative path, for display. */
  file: string;
  /** Absolute path, for reading source. */
  absFile: string;
  startLine: number;
  endLine: number;
  score: number;
  tier: string;
  breakdown?: RiskBreakdown;
  fanIn: number;
  fanOut: number;
  coverage: string;
  coverageIsProxy: boolean;
  churnCount: number;
  busFactor: number;
  gitResolved: boolean;
  authors: { name: string; email: string; commits: number }[];
  commits: { hash: string; name: string; t: number; subject: string }[];
  callers: string[];
  callees: string[];
}

export interface LlmContext {
  functions: Map<string, FunctionInfo>;
  features: FeaturesPayload | null;
  /** Lines [start, end] (0-based, inclusive) of a file, or null if unreadable. */
  readLines: (absFile: string, start: number, end: number) => string[] | null;
  generatedAt: Date;
  /** Keep a single document from swamping a context window. */
  maxLinesPerFunction?: number;
  maxSourceLines?: number;
}

const FENCE: Record<string, string> = {
  ".js": "javascript", ".jsx": "jsx", ".mjs": "javascript", ".cjs": "javascript",
  ".ts": "typescript", ".tsx": "tsx", ".mts": "typescript", ".cts": "typescript",
  ".go": "go", ".sql": "sql", ".prisma": "prisma",
};

function fenceFor(file: string): string {
  const dot = file.lastIndexOf(".");
  return dot === -1 ? "" : FENCE[file.slice(dot).toLowerCase()] || "";
}

function day(t: number): string {
  return t ? new Date(t).toISOString().slice(0, 10) : "unknown";
}

function loc(fn: { file: string; startLine: number; endLine?: number }): string {
  return `${fn.file}:${fn.startLine + 1}${fn.endLine !== undefined && fn.endLine > fn.startLine ? `-${fn.endLine + 1}` : ""}`;
}

/** Escape text for a Markdown table cell. */
function cell(text: string | number): string {
  return String(text).replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

export function slugify(text: string): string {
  return (
    text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "untitled"
  );
}

function riskLine(fn: FunctionInfo): string {
  const parts = [
    `${fn.fanIn} caller${fn.fanIn === 1 ? "" : "s"}`,
    `coverage ${fn.coverage}${fn.coverageIsProxy ? " (name proxy, not measured)" : ""}`,
    `${fn.churnCount} change${fn.churnCount === 1 ? "" : "s"} in 90 days`,
  ];
  if (fn.gitResolved) {
    parts.push(`bus factor ${fn.busFactor}`);
  }
  return parts.join(", ");
}

/** Code block for one function, trimmed to the per-function cap. */
function sourceBlock(fn: FunctionInfo, ctx: LlmContext, budget: { left: number }): string[] {
  const cap = ctx.maxLinesPerFunction ?? 150;
  const wanted = fn.endLine - fn.startLine + 1;
  if (budget.left <= 0) {
    return [`_Source omitted to keep this document a usable size - read it at \`${loc(fn)}\`._`];
  }
  const take = Math.min(wanted, cap, budget.left);
  const lines = ctx.readLines(fn.absFile, fn.startLine, fn.startLine + take - 1);
  if (!lines) {
    return [`_Source unavailable (file unreadable or moved) - expected at \`${loc(fn)}\`._`];
  }
  budget.left -= lines.length;
  const out = ["```" + fenceFor(fn.file), ...lines, "```"];
  if (take < wanted) {
    out.push(`_Showing ${take} of ${wanted} lines - the rest is at \`${loc(fn)}\`._`);
  }
  return out;
}

function header(title: string, ctx: LlmContext): string[] {
  return [
    `# ${title}`,
    "",
    `> Generated by Blast Radius on ${ctx.generatedAt.toISOString().slice(0, 16).replace("T", " ")} UTC from the call graph, ` +
      "git history and risk scores. Every statement below is measured, not inferred - but code changes after this " +
      "was generated are not reflected, so check the source before relying on line numbers.",
    "",
  ];
}

/* ------------------------------------------------------------- function */

export function functionMarkdown(id: string, ctx: LlmContext): string {
  const fn = ctx.functions.get(id);
  if (!fn) {
    return `# Unknown function\n\n\`${id}\` is not in the current index.\n`;
  }
  const lookup = (ids: string[]) => ids.map((x) => ctx.functions.get(x)).filter((x): x is FunctionInfo => !!x);
  const callers = lookup(fn.callers).sort((a, b) => b.score - a.score);
  const callees = lookup(fn.callees).sort((a, b) => b.score - a.score);

  // Everything that reaches this function through the call graph, however indirectly.
  const reach = new Set<string>();
  const queue = [...fn.callers];
  while (queue.length) {
    const next = queue.shift() as string;
    if (reach.has(next) || next === fn.id) {
      continue;
    }
    reach.add(next);
    queue.push(...(ctx.functions.get(next)?.callers || []));
  }

  const memberOf = (ctx.features?.features || []).filter((f) => f.functions.some((x) => x.id === fn.id));
  const lead = fn.authors[0];

  const out = header(fn.name, ctx);
  out.push(
    `- File: ${loc(fn)}`,
    `- Tier: ${fn.tier.toUpperCase()}${fn.breakdown && fn.breakdown.usage !== "active" ? ` (${fn.breakdown.usage})` : ""}`,
    `- Risk score: ${fn.score}`,
    `- Coverage: ${fn.coverage}${fn.coverageIsProxy ? " (proxy)" : ""}`,
    `- Fan-in: ${fn.fanIn}`,
    `- Fan-out: ${fn.fanOut}`,
    `- Churn 90d: ${fn.churnCount}`,
    `- Bus factor: ${fn.gitResolved ? fn.busFactor : "unknown"}`,
    "",
    "## Summary",
    `\`${fn.name}\` has ${callers.length} direct caller${callers.length === 1 ? "" : "s"} and ` +
      `${callees.length} direct callee${callees.length === 1 ? "" : "s"}. ` +
      `Changing it can reach ${reach.size} function${reach.size === 1 ? "" : "s"} through the call graph.` +
      (memberOf.length ? ` It belongs to ${memberOf.length === 1 ? "the feature" : "the features"} ${memberOf.map((f) => `"${f.name}"`).join(", ")}.` : ""),
    "",
    "## Source",
    ...sourceBlock(fn, ctx, { left: ctx.maxSourceLines ?? 2000 }),
    "",
    "## Callers",
    ...(callers.length ? callers.map((c) => `- \`${c.name}\` (${loc(c)}) - risk ${c.score}`) : ["- None in this workspace"]),
    "",
    "## Calls",
    ...(callees.length ? callees.map((c) => `- \`${c.name}\` (${loc(c)}) - risk ${c.score}`) : ["- None in this workspace"]),
    "",
  );

  if (memberOf.length) {
    out.push("## Features", "");
    for (const f of memberOf) {
      out.push(`- **${f.name}** (${f.primaryType}) - ${f.commits.length} commit${f.commits.length === 1 ? "" : "s"}, ${f.authors.map((a) => a.name).join(", ")}`);
    }
    out.push("");
  }

  if (fn.commits.length) {
    out.push("## Recent history", "", "| Commit | Date | Author | Message |", "|---|---|---|---|");
    for (const c of fn.commits.slice(0, 15)) {
      out.push(`| ${c.hash} | ${day(c.t)} | ${cell(c.name)} | ${cell(c.subject)} |`);
    }
    out.push("");
  }

  out.push(
    "## Risk notes",
    `- ${riskLine(fn)}`,
    `- Coverage proxy: ${fn.coverageIsProxy ? "yes" : "no"}`,
    `- Git resolved: ${fn.gitResolved ? "yes" : "no"}`,
    `- Primary author: ${lead ? `${lead.name} <${lead.email}> (${lead.commits} commits)` : "none recorded"}`,
  );
  if (fn.gitResolved && fn.busFactor === 1) {
    out.push("- Only one person has ever changed these lines.");
  }
  out.push(
    "",
    "## Score formula",
    fn.breakdown ? formulaText(fn.breakdown) : `risk ${fn.score}`,
    "",
  );
  return out.join("\n");
}

/* -------------------------------------------------------------- feature */

export function featureMarkdown(key: string, ctx: LlmContext): string {
  const feature = ctx.features?.features.find((f) => f.key === key);
  if (!feature) {
    return `# Unknown feature\n\n\`${key}\` is not in the current feature list.\n`;
  }
  const members = feature.functions
    .map((x) => ctx.functions.get(x.id))
    .filter((x): x is FunctionInfo => !!x)
    .sort((a, b) => b.score - a.score);
  const memberIds = new Set(members.map((m) => m.id));

  // How the feature's functions relate to each other and to the rest of the code.
  const internal: string[] = [];
  const entryPoints = new Map<string, FunctionInfo[]>();
  const dependsOn = new Map<string, { fn: FunctionInfo; usedBy: Set<string> }>();
  for (const fn of members) {
    for (const calleeId of fn.callees) {
      const callee = ctx.functions.get(calleeId);
      if (!callee) continue;
      if (memberIds.has(calleeId)) {
        internal.push(`\`${fn.name}\` -> \`${callee.name}\``);
      } else {
        const entry = dependsOn.get(calleeId) || { fn: callee, usedBy: new Set<string>() };
        entry.usedBy.add(fn.name);
        dependsOn.set(calleeId, entry);
      }
    }
    const outside = fn.callers.map((c) => ctx.functions.get(c)).filter((c): c is FunctionInfo => !!c && !memberIds.has(c.id));
    if (outside.length) {
      entryPoints.set(fn.id, outside);
    }
  }

  const typeSummary = Object.entries(feature.typeCounts)
    .map(([type, n]) => `${type} (${n})`)
    .join(", ");
  const lead = feature.authors[0];
  const riskiest = members[0];

  const out = header(`Feature: ${feature.name}`, ctx);
  out.push(
    "## At a glance",
    "",
    "| | |",
    "|---|---|",
    `| Type | ${cell(typeSummary)} |`,
    `| Scope | ${cell(feature.scope || "none - grouped by commit title")} |`,
    `| Active | ${day(feature.firstChange)} to ${day(feature.lastChange)} |`,
    `| Commits | ${feature.commits.length} |`,
    `| People | ${cell(feature.authors.map((a) => `${a.name} (${a.commits})`).join(", "))} |`,
    `| Ask first | ${lead ? cell(`${lead.name} <${lead.email}>`) : "unknown"} |`,
    `| Files | ${feature.files.length} |`,
    `| Functions | ${members.length} |`,
    `| Highest risk | ${riskiest ? cell(`${riskiest.name} - ${riskiest.score} (${riskiest.tier})`) : "none"} |`,
    "",
    "## What this feature is",
    "",
    "Its commits, oldest first. These are the only description of intent Blast Radius has - they are the authors' own words.",
    "",
  );
  for (const c of feature.commits.slice().reverse()) {
    out.push(`- ${day(c.t)} **${c.type}**: ${c.title} - ${c.author}${c.breaking ? " - BREAKING CHANGE" : ""}`);
  }

  out.push("", "## Where the code lives", "", "### Files", "");
  for (const f of feature.files) {
    out.push(`- \`${f.path}\` - ${f.commits} commit${f.commits === 1 ? "" : "s"}`);
  }

  out.push("", "### Functions", "");
  if (members.length) {
    out.push("| Function | Location | Risk | Callers | Calls | Coverage |", "|---|---|---|---|---|---|");
    for (const fn of members) {
      out.push(`| \`${cell(fn.name)}\` | ${cell(loc(fn))} | ${fn.score} (${fn.tier}) | ${fn.fanIn} | ${fn.fanOut} | ${cell(fn.coverage)} |`);
    }
  } else {
    out.push(
      "_No indexed function's line history includes this feature's commits. They may only touch files Blast Radius does " +
        "not index (styles, config, SQL), or history was still loading when this was generated._",
    );
  }

  out.push("", "## How it fits together", "");
  out.push("### Calls inside the feature", "");
  out.push(...(internal.length ? internal.map((x) => `- ${x}`) : ["- None - the feature's functions do not call one another."]));

  out.push("", "### Called from outside the feature", "");
  out.push(
    "Code that is not part of this feature but calls into it. Changing the feature can break these - " +
      "check them before changing a signature or behaviour.",
    "",
  );
  if (entryPoints.size) {
    for (const [id, outside] of entryPoints) {
      const fn = ctx.functions.get(id) as FunctionInfo;
      out.push(`- \`${fn.name}\` is called by ${outside.map((o) => `\`${o.name}\` (${loc(o)})`).join(", ")}`);
    }
  } else {
    out.push("- Nothing outside the feature calls into it.");
  }

  out.push("", "### What the feature depends on", "");
  if (dependsOn.size) {
    for (const { fn, usedBy } of dependsOn.values()) {
      out.push(`- \`${fn.name}\` (${loc(fn)}) - used by ${[...usedBy].map((n) => `\`${n}\``).join(", ")}`);
    }
  } else {
    out.push("- Nothing outside the feature.");
  }

  out.push("", "## Risks to keep in mind", "");
  const risky = members.filter((m) => m.tier === "high" || m.tier === "critical" || (m.gitResolved && m.busFactor === 1));
  if (risky.length) {
    for (const fn of risky) {
      out.push(`- \`${fn.name}\` - ${fn.tier.toUpperCase()} (${fn.score}): ${riskLine(fn)}`);
    }
  } else {
    out.push("- No high-risk or single-owner functions.");
  }
  if (members.some((m) => m.coverageIsProxy)) {
    out.push("- Coverage figures here are a name proxy - no lcov report was available - not measured coverage.");
  }

  out.push("", "## Source", "");
  const budget = { left: ctx.maxSourceLines ?? 2000 };
  for (const fn of members) {
    out.push(`### ${fn.name} - ${loc(fn)}`, "", ...sourceBlock(fn, ctx, budget), "");
  }
  if (!members.length) {
    out.push("_No functions to show._", "");
  }

  out.push("## History", "", "| Commit | Date | Author | Type | Message | Files |", "|---|---|---|---|---|---|");
  for (const c of feature.commits) {
    out.push(`| ${c.hash} | ${day(c.t)} | ${cell(c.author)} | ${c.type} | ${cell(c.title)} | ${c.files.length} |`);
  }
  out.push("");
  return out.join("\n");
}

/* ---------------------------------------------------------------- index */

/**
 * One file name per feature, unique even when two features slug the same way
 * (a scope "users" and a title "Users!"), so an export never overwrites itself.
 */
export function assignFeatureFileNames(features: { key: string; name: string }[]): Map<string, string> {
  const names = new Map<string, string>();
  const used = new Set<string>();
  for (const f of features) {
    const base = slugify(f.name);
    let name = `${base}.md`;
    for (let n = 2; used.has(name); n++) {
      name = `${base}-${n}.md`;
    }
    used.add(name);
    names.set(f.key, name);
  }
  return names;
}

export function featuresIndexMarkdown(features: Feature[], ctx: LlmContext, fileNames?: Map<string, string>): string {
  const names = fileNames || assignFeatureFileNames(features);
  const out = header("Features", ctx);
  const payload = ctx.features;
  if (payload) {
    out.push(
      `${features.length} feature${features.length === 1 ? "" : "s"} from ${payload.taggedCommits} of ` +
        `${payload.totalCommits} commits. Each has its own file in \`features/\`.`,
      "",
    );
  }
  out.push("| Feature | Type | Commits | People | Functions | Last change |", "|---|---|---|---|---|---|");
  for (const f of features) {
    out.push(
      `| [${cell(f.name)}](features/${names.get(f.key)}) | ${f.primaryType} | ${f.commits.length} | ` +
        `${cell(f.authors.map((a) => a.name).join(", "))} | ${f.functions.length} | ${day(f.lastChange)} |`,
    );
  }
  out.push("");
  return out.join("\n");
}

export function functionFileName(fn: { name: string; file: string }): string {
  return `${slugify(fn.file.replace(/\.[^.]+$/, ""))}--${slugify(fn.name)}.md`;
}
